2025-03-18 01:11:55,501 - PythonTestLogger - ERROR - Test failed for QA6_P11_P12.py on QA6

SRNs: P11/P12

Error:
Traceback (most recent call last):
  File "/Volumes/Aditya SSD/Project/AutomaticPythonTesting/AutomaticPythonTesting/scripts/QA6_P11_P12.py", line 3, in <module>
    from sympy import Matrix
ModuleNotFoundError: No module named 'sympy'


Test Type: stdin

Test Input:
2 2
1 2
0 1
2 1
2
3

Expected Output:
P' =
8.0
3.0

RREF =
1.0 0.0
0.0 1.0

T^-1 =
1.000 -2.000
0.000 1.000
--------------------------------------------------
2025-03-18 01:11:55,818 - PythonTestLogger - ERROR - Test failed for QA6_P11_P12.py on QA6

SRNs: P11/P12

Error:
Traceback (most recent call last):
  File "/Volumes/Aditya SSD/Project/AutomaticPythonTesting/AutomaticPythonTesting/scripts/QA6_P11_P12.py", line 3, in <module>
    from sympy import Matrix
ModuleNotFoundError: No module named 'sympy'


Test Type: stdin

Test Input:
3 3
3 1 2
4 2 1
1 2 3
3 1
1
0
1


Expected Output:
P' =
5.0
5.0
4.0

RREF =
1.0 0.0 0.0
0.0 1.0 0.0
0.0 0.0 1.0

T^-1 =
0.308 0.077 -0.231
-0.846 0.538 0.385
0.462 -0.385 0.154
--------------------------------------------------
2025-03-18 01:11:56,130 - PythonTestLogger - ERROR - Test failed for QA6_P11_P12.py on QA6

SRNs: P11/P12

Error:
Traceback (most recent call last):
  File "/Volumes/Aditya SSD/Project/AutomaticPythonTesting/AutomaticPythonTesting/scripts/QA6_P11_P12.py", line 3, in <module>
    from sympy import Matrix
ModuleNotFoundError: No module named 'sympy'


Test Type: stdin

Test Input:
4 4
2 3 1 4
1 5 3 2
4 2 6 5
3 1 2 3
4 1
5
6
7
8

Expected Output:
P' =
67.0
72.0
114.0
59.0

RREF =
1.0 0.0 0.0 0.0
0.0 1.0 0.0 0.0
0.0 0.0 1.0 0.0
0.0 0.0 0.0 1.0

T^-1 =
-0.407 0.185 -0.370 1.037
-0.037 0.259 -0.185 0.185
-0.148 0.037 0.259 -0.259
0.519 -0.296 0.259 -0.593

--------------------------------------------------
2025-03-18 01:11:56,451 - PythonTestLogger - ERROR - Test failed for QA7_P13_P14.py on QA7

SRNs: P13/P14

Error:
Traceback (most recent call last):
  File "/Volumes/Aditya SSD/Project/AutomaticPythonTesting/AutomaticPythonTesting/scripts/QA7_P13_P14.py", line 3, in <module>
    from sympy import Matrix
ModuleNotFoundError: No module named 'sympy'


Test Type: stdin

Test Input:
3 4
1 -1 0 0
0 1 -1 0
0 0 1 -1

Expected Output:
RREF =
1.0 0.0 0.0 -1.0
0.0 1.0 0.0 -1.0
0.0 0.0 1.0 -1.0

Rank = 3
Nullity = 1
--------------------------------------------------
2025-03-18 01:11:56,746 - PythonTestLogger - ERROR - Test failed for QA7_P13_P14.py on QA7

SRNs: P13/P14

Error:
Traceback (most recent call last):
  File "/Volumes/Aditya SSD/Project/AutomaticPythonTesting/AutomaticPythonTesting/scripts/QA7_P13_P14.py", line 3, in <module>
    from sympy import Matrix
ModuleNotFoundError: No module named 'sympy'


Test Type: stdin

Test Input:
3 3
1 2 3
4 5 6
7 8 10

Expected Output:
RREF =
1.0 0.0 0.0
0.0 1.0 0.0
0.0 0.0 1.0

Rank = 3
Nullity = 0
--------------------------------------------------
2025-03-18 01:11:57,047 - PythonTestLogger - ERROR - Test failed for QA7_P13_P14.py on QA7

SRNs: P13/P14

Error:
Traceback (most recent call last):
  File "/Volumes/Aditya SSD/Project/AutomaticPythonTesting/AutomaticPythonTesting/scripts/QA7_P13_P14.py", line 3, in <module>
    from sympy import Matrix
ModuleNotFoundError: No module named 'sympy'


Test Type: stdin

Test Input:
4 5
1 0 -1 2 3
0 1 1 0 -1
1 1 0 -1 4
2 -1 3 1 0

Expected Output:
RREF =
1.0 0.0 0.0 0.0 2.8
0.0 1.0 0.0 0.0 0.5
0.0 0.0 1.0 0.0 -1.5
0.0 0.0 0.0 1.0 -0.7

Rank = 4
Nullity = 1

--------------------------------------------------
2025-03-18 01:11:57,301 - PythonTestLogger - ERROR - Test failed for QA8_P15_P16.py on QA8

SRNs: P15/P16

Error:
Traceback (most recent call last):
  File "/Volumes/Aditya SSD/Project/AutomaticPythonTesting/AutomaticPythonTesting/scripts/QA8_P15_P16.py", line 3, in <module>
    from sympy import Matrix
ModuleNotFoundError: No module named 'sympy'


Test Type: stdin

Test Input:
2 2
2 1
3 4
2 2
5 6
7 8

Expected Output:
C =
2.6 3.2
-0.2 -0.4

RREF =
1.0 0.0
0.0 1.0

Rank = 2
Nullity = 0
--------------------------------------------------
2025-03-18 01:11:57,595 - PythonTestLogger - ERROR - Test failed for QA8_P15_P16.py on QA8

SRNs: P15/P16

Error:
Traceback (most recent call last):
  File "/Volumes/Aditya SSD/Project/AutomaticPythonTesting/AutomaticPythonTesting/scripts/QA8_P15_P16.py", line 3, in <module>
    from sympy import Matrix
ModuleNotFoundError: No module named 'sympy'


Test Type: stdin

Test Input:
3 3
3 1 2
4 2 1
1 2 3
3 2
6 9
3 7
8 5


Expected Output:
C =
0.2 2.2
-0.4 -1.9
2.8 2.2

RREF =
1.0 0.0 0.0
0.0 1.0 0.0
0.0 0.0 1.0

Rank = 3
Nullity = 0
--------------------------------------------------
2025-03-18 01:11:57,898 - PythonTestLogger - ERROR - Test failed for QA8_P15_P16.py on QA8

SRNs: P15/P16

Error:
Traceback (most recent call last):
  File "/Volumes/Aditya SSD/Project/AutomaticPythonTesting/AutomaticPythonTesting/scripts/QA8_P15_P16.py", line 3, in <module>
    from sympy import Matrix
ModuleNotFoundError: No module named 'sympy'


Test Type: stdin

Test Input:
4 4
2 3 1 4
1 5 3 2
4 2 6 5
3 1 2 3
4 2
5 6
7 8
9 10
11 12

Expected Output:
C =
7.3 7.8
2.0 2.2
-1.0 -1.1
-3.7 -3.8

RREF =
1.0 0.0 0.0 0.0
0.0 1.0 0.0 0.0
0.0 0.0 1.0 0.0
0.0 0.0 0.0 1.0

Rank = 4
Nullity = 0

--------------------------------------------------
2025-03-18 01:12:00,063 - PythonTestLogger - ERROR - Test failed for QF6_P19_P20.py on QF6

SRNs: P19/P20

Error:
Traceback (most recent call last):
  File "/Volumes/Aditya SSD/Project/AutomaticPythonTesting/AutomaticPythonTesting/scripts/QF6_P19_P20.py", line 3, in <module>
    from sympy import Matrix
ModuleNotFoundError: No module named 'sympy'


Test Type: stdin

Test Input:
3 3
1 2 -1
2 4 -2
3 6 -3

Expected Output:
RREF =
1.0 2.0 -1.0
0.0 0.0 0.0
0.0 0.0 0.0
--------------------------------------------------
2025-03-18 01:12:00,408 - PythonTestLogger - ERROR - Test failed for QF6_P19_P20.py on QF6

SRNs: P19/P20

Error:
Traceback (most recent call last):
  File "/Volumes/Aditya SSD/Project/AutomaticPythonTesting/AutomaticPythonTesting/scripts/QF6_P19_P20.py", line 3, in <module>
    from sympy import Matrix
ModuleNotFoundError: No module named 'sympy'


Test Type: stdin

Test Input:
3 3
1 2 3
0 1 4
5 6 0

Expected Output:
RREF =
1.0 0.0 0.0
0.0 1.0 0.0
0.0 0.0 1.0
--------------------------------------------------
2025-03-18 01:12:00,749 - PythonTestLogger - ERROR - Test failed for QF6_P19_P20.py on QF6

SRNs: P19/P20

Error:
Traceback (most recent call last):
  File "/Volumes/Aditya SSD/Project/AutomaticPythonTesting/AutomaticPythonTesting/scripts/QF6_P19_P20.py", line 3, in <module>
    from sympy import Matrix
ModuleNotFoundError: No module named 'sympy'


Test Type: stdin

Test Input:
3 4
4 7 2 5
2 6 5 8
1 3 1 4

Expected Output:
RREF =
1.0 0.0 0.0 -2.6
0.0 1.0 0.0 2.2
0.0 0.0 1.0 0.0
--------------------------------------------------
